# codemagic.yaml
# Versão FINAL, DEPURADA E SIMPLIFICADA para construir o APK do EchoTap.
# Esta configuração utiliza as diretivas nativas do Codemagic para configurar o ambiente,
# evitando erros de 'command not found'.

workflows:
  android-debug-build:
    name: EchoTap - Android Debug Build
    instance_type: mac_mini_m1
    
    # A maneira CORRETA e DECLARATIVA de configurar o ambiente Android.
    # Isto garante que o SDK e as ferramentas de build estejam prontos antes dos scripts rodarem.
    android:
      # PONTO CHAVE DA CORREÇÃO:
      # Especifica a versão exata do Build Tools necessária.
      # Codemagic irá instalar e configurar isso automaticamente.
      build_tools: 33.0.2

    scripts:
      - name: Instalar dependências e CLI do Cordova
        script: | 
          # Boa prática: definir uma versão estável do Node.js
          nvm install 20
          npm install -g cordova
          npm install

      - name: Construir o APK de teste (Debug)
        script: | 
          cordova build android --debug
          
    artifacts:
      # O caminho para o artefato está correto.
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk