# codemagic.yaml
# Versão FINAL E CORRIGIDA do fluxo de trabalho.
# Adiciona o comando 'cordova platform add' para garantir que a estrutura
# do projeto esteja completa antes da compilação.

workflows:
  android-debug-build:
    name: EchoTap - Android Debug Build
    instance_type: mac_mini_m1

    scripts:
      - name: Instalar Android build-tools v33.0.2
        script: | 
          # Este passo está correto e deve ser mantido.
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"

      - name: Instalar dependências e CLI do Cordova
        script: | 
          nvm install 20
          npm install -g cordova
          npm install

      - name: Adicionar plataforma Android
        script: | 
          # ESTE É O PASSO CRUCIAL QUE ESTAVA FALTANDO.
          # Ele cria a pasta 'platforms/android' e prepara o projeto para o build.
          cordova platform add android@12.0.0
          
      - name: Construir o APK de teste (Debug)
        script: | 
          cordova build android --debug
          
    artifacts:
      # O caminho para o artefato está correto.
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk