# codemagic.yaml
# Versão FINAL E CORRIGIDA do fluxo de trabalho para construir o APK de depuração do EchoTap.
# Este arquivo respeita o esquema de validação do Codemagic e resolve o erro de build original.

workflows:
  android-debug-build:
    name: EchoTap - Android Debug Build
    instance_type: mac_mini_m1
      
    environment:
      # A maneira CORRETA de incluir as variáveis de ambiente do Android SDK.
      groups:
        - android-sdk

    scripts:
      - name: Configurar ambiente de build (Java e Android SDK)
        script: | 
          # 1. Define a versão do Java usando jenv (ferramenta padrão no macOS da Codemagic)
          # cordova-android@12 requer JDK 11.
          echo "Setting Java version to 11..."
          jenv global 11.0
          
          # 2. Aceita as licenças do SDK para permitir a instalação de novos pacotes.
          echo "Accepting Android SDK licenses..."
          yes | sdkmanager --licenses >/dev/null
          
          # 3. Instala a versão EXATA do build-tools que o erro original exigia.
          echo "Installing Android build-tools v33.0.2..."
          sdkmanager "build-tools;33.0.2"

      - name: Instalar dependências e CLI do Cordova
        script: | 
          # Instala o Node.js na versão LTS mais recente (boa prática)
          nvm install 20
          npm install -g cordova
          npm install

      - name: Construir o APK de teste (Debug)
        script: | 
          cordova build android --debug
          
    artifacts:
      # O caminho para o artefato está correto.
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk