# codemagic.yaml
# Versão FINAL E CORRIGIDA do fluxo de trabalho.
# Resolve o erro de build-tools usando o caminho completo para o sdkmanager,
# garantindo compatibilidade e validade do arquivo de configuração.

workflows:
  android-debug-build:
    name: EchoTap - Android Debug Build
    instance_type: mac_mini_m1

    scripts:
      - name: Instalar Android build-tools v33.0.2
        script: | 
          # FATO: $ANDROID_HOME é uma variável de ambiente padrão nos ambientes Codemagic.
          # SOLUÇÃO: Usamos o caminho completo para o sdkmanager para evitar erros de "command not found".
          
          echo "Accepting Android SDK licenses..."
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null
          
          echo "Installing Android build-tools v33.0.2..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"

      - name: Instalar dependências e CLI do Cordova
        script: | 
          # Define a versão do Node.js para consistência
          nvm install 20
          npm install -g cordova
          npm install

      - name: Construir o APK de teste (Debug)
        script: | 
          cordova build android --debug
          
    artifacts:
      # O caminho para o artefato está correto.
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk